### ISSUE TITLE
Wishlist for Christmas

### ISSUE THREAD

**Issue by haakonstorm** [kevinjalbert/alfred-notion#2]
1. Universal Peace on the Planet
2. Understanding Quantum Mechanics
3. A General-Purpose Alfred Workflow for Notion
<3

**Comment by kevinjalbert** [comment]
@haakonstorm For sure I cannot help with 1 and 2 😉.

With respect to a _General-Purpose Alfred Workflow for Notion_ I think it is going to be a bit out of scope (at least immediately). My goal was to have a specific flow, for my specific template.

It might be something that could be added, although I'd likely not lead that charge as this project was to scratch a personal itch.

If you feel like doing something like this, go for it! I'll like to see what you come up with. I also would keep my eyes out for the official Notion API coming out at some point soon.
